### PR TITLE
Downgrade `frequenz-api-common` version to 0.5.3

### PR DESCRIPTION
**Pull request by shsms**
This is to make this package compatible with current versions of the
SDK.

### CODE REVIEW

**Comment by shsms** [comment]
Sorry, this reverts an upgrade I made in a previous PR.  Because there were multiple links in the dependency chain, I didn't realize this was an issue until now.

**Comment by shsms** [comment]
With this I've verified that everything works.

**Review by nhatcher-frequenz — APPROVED** [review]
LGTM!

PS: It's a shame

**Comment by nhatcher-frequenz** [comment]
(merging as you don't have write access).

FYI: @camille-bouvy-frequenz

**Pull request merged**
